### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by benjaminclot**

### CODE REVIEW

**Comment by j0nes2k** [comment]
@krishoyt Is the new UI already translateable? I don't see any localization functions in the banner component - or am I simply missing something?

**Comment by Broutard** [comment]
After the yesterday commit (new-ui), it break all translations.
My entire UI is in EN now :(

**Comment by ddelrue** [comment]
Translation did not work and how about multilingual sites ?

**Comment by Broutard** [comment]
All translations must be re-writed after the last MR (new UI)

**Comment by j0nes2k** [comment]
As I said, the new UI does not seem to be translateable yet. So it is not only a matter of providing new translations, but also to provide a mechanism to allow localization at all.

**Comment by krishoyt** [comment]
I didn't have any translations for the new UI components so I neglected to wrap text fields with `LocalLabel` components and create new `localizeKey` entries. This will need to be done before any translations will show up.

**Pull request closed without merging**
