### PR TITLE
Mobile responsiveness, various banner/popup copy changes & tweaks

### PR DESCRIPTION
**Pull request by mdurrant**
Thank you for creating this project. We're using it to roll out our GDPR consent in our ad framework this week. In order to use it I had to make quite a few changes - changes that I hope align with your vision.

**Issue 1: Mobile Responsiveness**
As you know, mobile usage has reached the point where it surpasses desktops on many sites. It's important for the consent box to be fully visible, functional and readable on all mobile screens. I did a ground-up overhaul of the banner component to look good on portrait and landscape phones. The popup component required some changes but they weren't as substantial as the banner.

You can see the before/after shot here:
ba-phone

**Issue 2: Custom Themes**
Currently it is possible to some extent to modify the less variables and customize the appearance of the consent prompt. I have added a new theme config object to `cmp` that allows sites to match it to the look & feel of their site from code. This will allow prebid wrappers that bundle your consent framework or sites that just use your script off a cdn to easily style it without needing to build it for each site.

For example:

```
cmp.config = {
    theme: {
        overlayBackground: 'rgba(0, 0, 0, 0.84)',
        primary: '#945dff',
        primaryText: '#fff',
        secondary: '#555',
        secondaryText: '#ccc',
        textLink: '#945dff',
        background: '#fff',
        text: '#444',
        textLight: '#777',
        divider: '#999',
    }
}
```

Will produce a style like this

ba-style

**Issue 3: Copy Changes**
I took the liberty to make several copy changes - almost all were grammar issues like fixing a typo or rewording something to sound more natural.

---

I am open to change requests or questions. We intend on using our fork in production and then contributing to your project if you like what you see in this PR.

### CODE REVIEW

**Comment by theavish** [comment]
i like these changes, would love to see the PR accepted.

**Comment by lucop1** [comment]
hi! great job with the responsiveness but I tried to implement your branch. The issue is that translations now longer works.

**Comment by mdurrant** [comment]
The localization work was not merged to master when I opened this PR. There are new conflicts here that will need to get resolved for any of that stuff to work. I won't be able to get to it before the GDPR is in force - someone else is free to champion that effort if they can't wait a little while.

**Comment by mdurrant** [comment]
Closing this due to the work progressed in PR #70

**Pull request closed without merging**
